version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python_app:
    build:
      context: src/main/python
      dockerfile: dockerfile
    depends_on:
      - postgres
    volumes:
      - ./src/main/python:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres  # Name des PostgreSQL-Containers
      POSTGRES_PORT: 5432
    command: ["python", "fetcher.py"]

volumes:
  postgres_data:
    driver: local
