version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python_app:
    container_name: python_data_fetcher
    build:
      context: data_fetcher
      dockerfile: dockerfile
    depends_on:
      - postgres
    volumes:
      - ./data_fetcher:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres  # Name des PostgreSQL-Containers
      POSTGRES_PORT: 5432
      API_URL: ${API_URL}
      TIMEZONE: ${TIMEZONE}
    command: ["python", "-u", "fetcher.py"]

  springboot_app:
    build:
      context: backend
      dockerfile: dockerfile
    container_name: bike_backend
    depends_on:
      - postgres
    volumes:
      - ./backend/build/libs:/app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
    driver: local
